version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "88LAk+#9Dlb7Wb&SvrAra1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      timeout: 20s
      retries: 10
